server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_app_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=True
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

fileName: uploads

api:
  prefix: api/v1